/***************************************************************
 *
 * Interactive Demo: Colors in Digital Multimedia
 * Copyright (c) 2010 Dr. Andrew Kwok-Fai LUI
 * The Open University of Hong Kong
 *
 * Enhance the learning effectiveness of students through greater interactions
 */
/*  This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package faifai.color;

import helper.gui.SplashScreenFrame;
import helper.gui.TutorialFrame;
import java.awt.Color;

public class ColorMixLightDemo2D extends javax.swing.JFrame implements ColorSliderListener {

    private TutorialFrame tutorialFrame;

    /** Creates new form ColorSpaceDemo */
    public ColorMixLightDemo2D() {
        try {
            javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (Exception ex) {
        }
        initComponents();
        initColor();
        colorSliderPanel1.addColorSliderListener(this);
        colorSliderPanel2.addColorSliderListener(this);
        reflectionScenePanel2D1.setNumberOfLightSource(2);
        try {
            tutorialFrame = new TutorialFrame();
            tutorialFrame.loadText("/faifai/tutorial/ColorMixLightDemo.htm");
            tutorialFrame.showFrame();
        } catch (Exception ex) {
        }
    }

    private void initColor() {
        reflectionScenePanel2D1.setLightColor(new Color(colorSliderPanel1.getColor()));
        reflectionScenePanel2D1.setLightColorSecond(new Color(colorSliderPanel2.getColor()));
    }

    public void colorChanged(Object source, int red, int green, int blue) {
        if (source == colorSliderPanel1) {
            reflectionScenePanel2D1.setLightColor(new Color(colorSliderPanel1.getColor()));
        } else if (source == colorSliderPanel2) {
            reflectionScenePanel2D1.setLightColorSecond(new Color(colorSliderPanel2.getColor()));
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        colorSliderPanel1 = new faifai.color.ColorSliderPanel();
        colorSliderPanel2 = new faifai.color.ColorSliderPanel();
        reflectionScenePanel2D1 = new faifai.color.ReflectionScenePanel2D();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Light Mixing Reflection Demo");
        setMinimumSize(new java.awt.Dimension(360, 460));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        colorSliderPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
                "Light Source One Color Selector", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11),
                new java.awt.Color(255, 255, 255))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(colorSliderPanel1, gridBagConstraints);

        colorSliderPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
                "Light Source Two Color Selector", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11),
                new java.awt.Color(255, 255, 255))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(colorSliderPanel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(reflectionScenePanel2D1, gridBagConstraints);

        jMenuBar1.setBackground(new java.awt.Color(102, 0, 102));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 10));
        jMenu1.setOpaque(false);

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 10));
        jMenuItem1.setText("Quit");
        jMenuItem1.setOpaque(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Help");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 10));
        jMenu2.setOpaque(false);

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 10));
        jMenuItem3.setText("Tutorial");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 10));
        jMenuItem2.setText("About");
        jMenuItem2.setOpaque(false);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
        SplashScreenFrame.showFrame("/SplashScreenImage.png");
    }// GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
        tutorialFrame.showFrame();
    }// GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ColorMixLightDemo2D().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private faifai.color.ColorSliderPanel colorSliderPanel1;
    private faifai.color.ColorSliderPanel colorSliderPanel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private faifai.color.ReflectionScenePanel2D reflectionScenePanel2D1;
    // End of variables declaration//GEN-END:variables
}
