/***************************************************************
 *
 * Interactive Demo: Colors in Digital Multimedia
 * Copyright (c) 2010 Dr. Andrew Kwok-Fai LUI
 * The Open University of Hong Kong
 *
 * Enhance the learning effectiveness of students through greater interactions
 */
/*  This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package faifai.color;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JSlider;
import javax.swing.JTextField;

public class ColorSliderPanel extends javax.swing.JPanel {

  private int red = 128;
  private int green = 128;
  private int blue = 128;
  private ArrayList<ColorSliderListener> listenerList = new ArrayList<ColorSliderListener>();

  /**
   * Creates new form ColorSliderPanel
   */
  public ColorSliderPanel() {
    initComponents();
    jPanel5.setVisible(false);
    updateDisplay();
  }

  public int getColor() {
    return ((red << 16) + (green << 8) + blue) & 0x00ffffff;
  }

  public void setSelectedColor(int red, int green, int blue) {
    this.red = red;
    this.green = green;
    this.blue = blue;
  }

  public void setSelectedColor(int rgb) {
    this.red = (rgb >> 16) & 0xff;
    this.green = (rgb >> 8) & 0xff;
    this.blue = rgb & 0xff;
  }

  public void updateDisplay() {
    updateRGBSlider(this.red, jSlider1);
    updateRGBTextField(this.red, jTextField1, jTextField2);
    updateRGBSlider(this.green, jSlider2);
    updateRGBTextField(this.green, jTextField3, jTextField4);
    updateRGBSlider(this.blue, jSlider3);
    updateRGBTextField(this.blue, jTextField5, jTextField6);
    if (jPanel5.isVisible()) {
      float hsl[] = Color.RGBtoHSB(this.red, this.green, this.blue, null);
      updateHSLControls(hsl[0], hsl[1], hsl[2]);
      updateHSLLabels(hsl[0], hsl[1], hsl[2]);
    }
  }

  public void updateHSLSlider() {
    if (jPanel5.isVisible()) {
      float hsl[] = Color.RGBtoHSB(this.red, this.green, this.blue, null);
      updateHSLControls(hsl[0], hsl[1], hsl[2]);
      updateHSLLabels(hsl[0], hsl[1], hsl[2]);
    }
  }

  private void updateRGBSlider(int value, JSlider theSlider) {
    theSlider.setValue(value);
  }

  private void updateRGBTextField(int value, JTextField dec, JTextField hex) {
    dec.setText(value + "");
    if (value < 16) {
      hex.setText("0" + Integer.toHexString(value).toUpperCase());
    } else {
      hex.setText(Integer.toHexString(value).toUpperCase());
    }
  }

  private int getHexValue(String text) {
    try {
      int value = Integer.parseInt(text, 16);
      if (value < 0 || value > 255) {
        return -1;
      }
      return value;
    } catch (Exception ex) {
      return -1;
    }
  }

  private int getDecValue(String text) {
    try {
      int value = Integer.parseInt(text, 10);
      if (value < 0 || value > 255) {
        return -1;
      }
      return value;
    } catch (Exception ex) {
      return -1;
    }
  }

  public void setVisibleColorChooser(boolean isVisible) {
    jPanel4.setVisible(isVisible);
  }

  public void setVisibleHSLChooser(boolean isVisible) {
    jPanel5.setVisible(isVisible);
  }

  public void addColorSliderListener(ColorSliderListener listener) {
    listenerList.add(listener);
  }

  private void callColorSliderListeners() {
    for (ColorSliderListener listener : listenerList) {
      listener.colorChanged(this, red, green, blue);
    }
  }

  private void updateHSLLabels(float hue, float saturation, float lightness) {
    jLabel5.setText("" + (int) (hue * 360 % 360));
    jLabel8.setText("" + saturation);
    jLabel11.setText("" + lightness);
  }

  private void updateHSLControls(float hue, float saturation, float lightness) {
    jSlider4.setValue((int) (hue * 100) % 100);
    jSlider5.setValue((int) saturation * 100);
    jSlider6.setValue((int) lightness * 100);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jSlider1 = new javax.swing.JSlider();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jSlider2 = new javax.swing.JSlider();
    jTextField3 = new javax.swing.JTextField();
    jTextField4 = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jSlider3 = new javax.swing.JSlider();
    jTextField5 = new javax.swing.JTextField();
    jTextField6 = new javax.swing.JTextField();
    jPanel4 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jButton8 = new javax.swing.JButton();
    jButton9 = new javax.swing.JButton();
    jButton10 = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();
    jButton12 = new javax.swing.JButton();
    jButton13 = new javax.swing.JButton();
    jButton14 = new javax.swing.JButton();
    jButton15 = new javax.swing.JButton();
    jButton16 = new javax.swing.JButton();
    jButton17 = new javax.swing.JButton();
    jButton18 = new javax.swing.JButton();
    jButton19 = new javax.swing.JButton();
    jButton20 = new javax.swing.JButton();
    jPanel5 = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    jSlider4 = new javax.swing.JSlider();
    jLabel5 = new javax.swing.JLabel();
    jPanel7 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    jSlider5 = new javax.swing.JSlider();
    jLabel8 = new javax.swing.JLabel();
    jPanel8 = new javax.swing.JPanel();
    jLabel10 = new javax.swing.JLabel();
    jSlider6 = new javax.swing.JSlider();
    jLabel11 = new javax.swing.JLabel();

    setBackground(new java.awt.Color(0, 0, 51));
    setMaximumSize(new java.awt.Dimension(360, 300));
    setMinimumSize(new java.awt.Dimension(360, 200));
    setPreferredSize(new java.awt.Dimension(360, 200));
    setLayout(new java.awt.GridBagLayout());

    jPanel1.setOpaque(false);
    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText("Red");
    jLabel1.setMaximumSize(new java.awt.Dimension(60, 20));
    jLabel1.setMinimumSize(new java.awt.Dimension(60, 20));
    jLabel1.setPreferredSize(new java.awt.Dimension(60, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel1.add(jLabel1, gridBagConstraints);

    jSlider1.setMajorTickSpacing(50);
    jSlider1.setMaximum(255);
    jSlider1.setMinorTickSpacing(10);
    jSlider1.setValue(128);
    jSlider1.setOpaque(false);
    jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSliderStateChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel1.add(jSlider1, gridBagConstraints);

    jTextField1.setBackground(new java.awt.Color(204, 255, 51));
    jTextField1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
    jTextField1.setForeground(new java.awt.Color(51, 51, 51));
    jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jTextField1.setMaximumSize(new java.awt.Dimension(40, 20));
    jTextField1.setMinimumSize(new java.awt.Dimension(40, 20));
    jTextField1.setPreferredSize(new java.awt.Dimension(40, 20));
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        decTextFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel1.add(jTextField1, gridBagConstraints);

    jTextField2.setBackground(new java.awt.Color(204, 255, 51));
    jTextField2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
    jTextField2.setForeground(new java.awt.Color(51, 51, 51));
    jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jTextField2.setMaximumSize(new java.awt.Dimension(40, 20));
    jTextField2.setMinimumSize(new java.awt.Dimension(40, 20));
    jTextField2.setPreferredSize(new java.awt.Dimension(40, 20));
    jTextField2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        hexTextFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel1.add(jTextField2, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(jPanel1, gridBagConstraints);

    jPanel2.setOpaque(false);
    jPanel2.setLayout(new java.awt.GridBagLayout());

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Green");
    jLabel2.setMaximumSize(new java.awt.Dimension(60, 20));
    jLabel2.setMinimumSize(new java.awt.Dimension(60, 20));
    jLabel2.setPreferredSize(new java.awt.Dimension(60, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel2.add(jLabel2, gridBagConstraints);

    jSlider2.setMajorTickSpacing(50);
    jSlider2.setMaximum(255);
    jSlider2.setMinorTickSpacing(10);
    jSlider2.setValue(128);
    jSlider2.setOpaque(false);
    jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSliderStateChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel2.add(jSlider2, gridBagConstraints);

    jTextField3.setBackground(new java.awt.Color(204, 255, 51));
    jTextField3.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
    jTextField3.setForeground(new java.awt.Color(51, 51, 51));
    jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jTextField3.setMaximumSize(new java.awt.Dimension(40, 20));
    jTextField3.setMinimumSize(new java.awt.Dimension(40, 20));
    jTextField3.setPreferredSize(new java.awt.Dimension(40, 20));
    jTextField3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        decTextFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel2.add(jTextField3, gridBagConstraints);

    jTextField4.setBackground(new java.awt.Color(204, 255, 51));
    jTextField4.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
    jTextField4.setForeground(new java.awt.Color(51, 51, 51));
    jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jTextField4.setMaximumSize(new java.awt.Dimension(40, 20));
    jTextField4.setMinimumSize(new java.awt.Dimension(40, 20));
    jTextField4.setPreferredSize(new java.awt.Dimension(40, 20));
    jTextField4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        hexTextFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel2.add(jTextField4, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(jPanel2, gridBagConstraints);

    jPanel3.setOpaque(false);
    jPanel3.setLayout(new java.awt.GridBagLayout());

    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel3.setText("Blue");
    jLabel3.setMaximumSize(new java.awt.Dimension(60, 20));
    jLabel3.setMinimumSize(new java.awt.Dimension(60, 20));
    jLabel3.setPreferredSize(new java.awt.Dimension(60, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel3.add(jLabel3, gridBagConstraints);

    jSlider3.setMajorTickSpacing(50);
    jSlider3.setMaximum(255);
    jSlider3.setMinorTickSpacing(10);
    jSlider3.setValue(128);
    jSlider3.setOpaque(false);
    jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSliderStateChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel3.add(jSlider3, gridBagConstraints);

    jTextField5.setBackground(new java.awt.Color(204, 255, 51));
    jTextField5.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
    jTextField5.setForeground(new java.awt.Color(51, 51, 51));
    jTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jTextField5.setMaximumSize(new java.awt.Dimension(40, 20));
    jTextField5.setMinimumSize(new java.awt.Dimension(40, 20));
    jTextField5.setPreferredSize(new java.awt.Dimension(40, 20));
    jTextField5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        decTextFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel3.add(jTextField5, gridBagConstraints);

    jTextField6.setBackground(new java.awt.Color(204, 255, 51));
    jTextField6.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
    jTextField6.setForeground(new java.awt.Color(51, 51, 51));
    jTextField6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jTextField6.setMaximumSize(new java.awt.Dimension(40, 20));
    jTextField6.setMinimumSize(new java.awt.Dimension(40, 20));
    jTextField6.setPreferredSize(new java.awt.Dimension(40, 20));
    jTextField6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        hexTextFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel3.add(jTextField6, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(jPanel3, gridBagConstraints);

    jPanel4.setMaximumSize(new java.awt.Dimension(200, 100));
    jPanel4.setMinimumSize(new java.awt.Dimension(200, 100));
    jPanel4.setOpaque(false);
    jPanel4.setPreferredSize(new java.awt.Dimension(200, 100));
    jPanel4.setLayout(new java.awt.GridBagLayout());

    jButton1.setBackground(new java.awt.Color(0, 0, 0));
    jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton1.setForeground(new java.awt.Color(255, 255, 0));
    jButton1.setText("Red");
    jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton1.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton1.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton1.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 0;
    jPanel4.add(jButton1, gridBagConstraints);

    jButton2.setBackground(new java.awt.Color(0, 0, 0));
    jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 0));
    jButton2.setText("Green");
    jButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton2.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton2.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton2.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 0;
    jPanel4.add(jButton2, gridBagConstraints);

    jButton3.setBackground(new java.awt.Color(0, 0, 0));
    jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton3.setForeground(new java.awt.Color(255, 255, 0));
    jButton3.setText("Blue");
    jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton3.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton3.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton3.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 0;
    jPanel4.add(jButton3, gridBagConstraints);

    jButton4.setBackground(new java.awt.Color(0, 0, 0));
    jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton4.setForeground(new java.awt.Color(255, 255, 0));
    jButton4.setText("White");
    jButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton4.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton4.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton4.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 0;
    jPanel4.add(jButton4, gridBagConstraints);

    jButton5.setBackground(new java.awt.Color(0, 0, 0));
    jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton5.setForeground(new java.awt.Color(255, 255, 0));
    jButton5.setText("Light Grey");
    jButton5.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton5.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton5.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton5.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    jPanel4.add(jButton5, gridBagConstraints);

    jButton6.setBackground(new java.awt.Color(0, 0, 0));
    jButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton6.setForeground(new java.awt.Color(255, 255, 0));
    jButton6.setText("Grey");
    jButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton6.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton6.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton6.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    jPanel4.add(jButton6, gridBagConstraints);

    jButton7.setBackground(new java.awt.Color(0, 0, 0));
    jButton7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton7.setForeground(new java.awt.Color(255, 255, 0));
    jButton7.setText("Dark Grey");
    jButton7.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton7.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton7.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton7.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    jPanel4.add(jButton7, gridBagConstraints);

    jButton8.setBackground(new java.awt.Color(0, 0, 0));
    jButton8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton8.setForeground(new java.awt.Color(255, 255, 0));
    jButton8.setText("Black");
    jButton8.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton8.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton8.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton8.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    jPanel4.add(jButton8, gridBagConstraints);

    jButton9.setBackground(new java.awt.Color(0, 0, 0));
    jButton9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton9.setForeground(new java.awt.Color(255, 255, 0));
    jButton9.setText("Maganta");
    jButton9.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton9.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton9.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton9.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 2;
    jPanel4.add(jButton9, gridBagConstraints);

    jButton10.setBackground(new java.awt.Color(0, 0, 0));
    jButton10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton10.setForeground(new java.awt.Color(255, 255, 0));
    jButton10.setText("Chestnut");
    jButton10.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton10.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton10.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton10.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton10.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 2;
    jPanel4.add(jButton10, gridBagConstraints);

    jButton11.setBackground(new java.awt.Color(0, 0, 0));
    jButton11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton11.setForeground(new java.awt.Color(255, 255, 0));
    jButton11.setText("Maroon");
    jButton11.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton11.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton11.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton11.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton11.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 2;
    jPanel4.add(jButton11, gridBagConstraints);

    jButton12.setBackground(new java.awt.Color(0, 0, 0));
    jButton12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton12.setForeground(new java.awt.Color(255, 255, 0));
    jButton12.setText("Mauve");
    jButton12.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton12.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton12.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton12.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton12.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 2;
    jPanel4.add(jButton12, gridBagConstraints);

    jButton13.setBackground(new java.awt.Color(0, 0, 0));
    jButton13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton13.setForeground(new java.awt.Color(255, 255, 0));
    jButton13.setText("Yellow");
    jButton13.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton13.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton13.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton13.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton13.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 3;
    jPanel4.add(jButton13, gridBagConstraints);

    jButton14.setBackground(new java.awt.Color(0, 0, 0));
    jButton14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton14.setForeground(new java.awt.Color(255, 255, 0));
    jButton14.setText("Sap Green");
    jButton14.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton14.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton14.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton14.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton14.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 3;
    jPanel4.add(jButton14, gridBagConstraints);

    jButton15.setBackground(new java.awt.Color(0, 0, 0));
    jButton15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton15.setForeground(new java.awt.Color(255, 255, 0));
    jButton15.setText("Lime");
    jButton15.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton15.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton15.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton15.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton15.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 3;
    jPanel4.add(jButton15, gridBagConstraints);

    jButton16.setBackground(new java.awt.Color(0, 0, 0));
    jButton16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton16.setForeground(new java.awt.Color(255, 255, 0));
    jButton16.setText("Forest Green");
    jButton16.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton16.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton16.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton16.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton16.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 3;
    jPanel4.add(jButton16, gridBagConstraints);

    jButton17.setBackground(new java.awt.Color(0, 0, 0));
    jButton17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton17.setForeground(new java.awt.Color(255, 255, 0));
    jButton17.setText("Cyan");
    jButton17.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton17.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton17.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton17.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton17.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 4;
    jPanel4.add(jButton17, gridBagConstraints);

    jButton18.setBackground(new java.awt.Color(0, 0, 0));
    jButton18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton18.setForeground(new java.awt.Color(255, 255, 0));
    jButton18.setText("Royal Blue");
    jButton18.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton18.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton18.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton18.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton18.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 4;
    jPanel4.add(jButton18, gridBagConstraints);

    jButton19.setBackground(new java.awt.Color(0, 0, 0));
    jButton19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton19.setForeground(new java.awt.Color(255, 255, 0));
    jButton19.setText("Klein Blue");
    jButton19.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton19.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton19.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton19.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton19.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 4;
    jPanel4.add(jButton19, gridBagConstraints);

    jButton20.setBackground(new java.awt.Color(0, 0, 0));
    jButton20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    jButton20.setForeground(new java.awt.Color(255, 255, 0));
    jButton20.setText("Indigo");
    jButton20.setMargin(new java.awt.Insets(2, 2, 2, 2));
    jButton20.setMaximumSize(new java.awt.Dimension(80, 20));
    jButton20.setMinimumSize(new java.awt.Dimension(80, 20));
    jButton20.setPreferredSize(new java.awt.Dimension(80, 20));
    jButton20.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        changeColor(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 4;
    jPanel4.add(jButton20, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
    add(jPanel4, gridBagConstraints);

    jPanel5.setBackground(new java.awt.Color(102, 0, 102));
    jPanel5.setOpaque(false);
    jPanel5.setLayout(new java.awt.GridBagLayout());

    jPanel6.setOpaque(false);
    jPanel6.setLayout(new java.awt.GridBagLayout());

    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel4.setText("Hue");
    jLabel4.setMaximumSize(new java.awt.Dimension(60, 20));
    jLabel4.setMinimumSize(new java.awt.Dimension(60, 20));
    jLabel4.setPreferredSize(new java.awt.Dimension(60, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel6.add(jLabel4, gridBagConstraints);

    jSlider4.setMajorTickSpacing(20);
    jSlider4.setMinorTickSpacing(5);
    jSlider4.setOpaque(false);
    jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        hueSliderStateChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel6.add(jSlider4, gridBagConstraints);

    jLabel5.setBackground(new java.awt.Color(255, 204, 102));
    jLabel5.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(51, 51, 51));
    jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jLabel5.setMaximumSize(new java.awt.Dimension(40, 20));
    jLabel5.setMinimumSize(new java.awt.Dimension(40, 20));
    jLabel5.setOpaque(true);
    jLabel5.setPreferredSize(new java.awt.Dimension(40, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 25);
    jPanel6.add(jLabel5, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel5.add(jPanel6, gridBagConstraints);

    jPanel7.setOpaque(false);
    jPanel7.setLayout(new java.awt.GridBagLayout());

    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel7.setText("Saturation");
    jLabel7.setMaximumSize(new java.awt.Dimension(60, 20));
    jLabel7.setMinimumSize(new java.awt.Dimension(60, 20));
    jLabel7.setPreferredSize(new java.awt.Dimension(60, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel7.add(jLabel7, gridBagConstraints);

    jSlider5.setMajorTickSpacing(20);
    jSlider5.setMinorTickSpacing(5);
    jSlider5.setOpaque(false);
    jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        hueSliderStateChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel7.add(jSlider5, gridBagConstraints);

    jLabel8.setBackground(new java.awt.Color(255, 204, 102));
    jLabel8.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(51, 51, 51));
    jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jLabel8.setMaximumSize(new java.awt.Dimension(40, 20));
    jLabel8.setMinimumSize(new java.awt.Dimension(40, 20));
    jLabel8.setOpaque(true);
    jLabel8.setPreferredSize(new java.awt.Dimension(40, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 25);
    jPanel7.add(jLabel8, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel5.add(jPanel7, gridBagConstraints);

    jPanel8.setOpaque(false);
    jPanel8.setLayout(new java.awt.GridBagLayout());

    jLabel10.setForeground(new java.awt.Color(255, 255, 255));
    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel10.setText("Brightness");
    jLabel10.setMaximumSize(new java.awt.Dimension(60, 20));
    jLabel10.setMinimumSize(new java.awt.Dimension(60, 20));
    jLabel10.setPreferredSize(new java.awt.Dimension(60, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    jPanel8.add(jLabel10, gridBagConstraints);

    jSlider6.setMajorTickSpacing(20);
    jSlider6.setMinorTickSpacing(5);
    jSlider6.setOpaque(false);
    jSlider6.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        hueSliderStateChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel8.add(jSlider6, gridBagConstraints);

    jLabel11.setBackground(new java.awt.Color(255, 204, 102));
    jLabel11.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(51, 51, 51));
    jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    jLabel11.setMaximumSize(new java.awt.Dimension(40, 20));
    jLabel11.setMinimumSize(new java.awt.Dimension(40, 20));
    jLabel11.setOpaque(true);
    jLabel11.setPreferredSize(new java.awt.Dimension(40, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 25);
    jPanel8.add(jLabel11, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel5.add(jPanel8, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
    add(jPanel5, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

    private void jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderStateChanged
      JSlider theSlider = (JSlider) evt.getSource();
      if (theSlider == jSlider1) {
        this.red = theSlider.getValue();
        updateRGBTextField(this.red, jTextField1, jTextField2);
      } else if (theSlider == jSlider2) {
        this.green = theSlider.getValue();
        updateRGBTextField(this.green, jTextField3, jTextField4);
      } else if (theSlider == jSlider3) {
        this.blue = theSlider.getValue();
        updateRGBTextField(this.blue, jTextField5, jTextField6);
      }
      callColorSliderListeners();
    }//GEN-LAST:event_jSliderStateChanged

    private void decTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decTextFieldActionPerformed
      JTextField theTextField = (JTextField) evt.getSource();
      int value = getDecValue(theTextField.getText());
      if (value == -1) {
        return;
      }
      if (theTextField == jTextField1) {
        this.red = value;
        updateRGBSlider(this.red, jSlider1);
        updateRGBTextField(this.red, jTextField1, jTextField2);
      } else if (theTextField == jTextField3) {
        this.green = value;
        updateRGBSlider(this.green, jSlider2);
        updateRGBTextField(this.green, jTextField3, jTextField4);
      } else if (theTextField == jTextField5) {
        this.blue = value;
        updateRGBSlider(this.blue, jSlider3);
        updateRGBTextField(this.blue, jTextField5, jTextField6);
      }
    }//GEN-LAST:event_decTextFieldActionPerformed

    private void hexTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexTextFieldActionPerformed
      JTextField theTextField = (JTextField) evt.getSource();
      int value = getHexValue(theTextField.getText());
      if (value == -1) {
        return;
      }
      if (theTextField == jTextField2) {
        this.red = value;
        updateRGBSlider(this.red, jSlider1);
        updateRGBTextField(this.red, jTextField1, jTextField2);
      } else if (theTextField == jTextField4) {
        this.green = value;
        updateRGBSlider(this.green, jSlider2);
        updateRGBTextField(this.green, jTextField3, jTextField4);
      } else if (theTextField == jTextField6) {
        this.blue = value;
        updateRGBSlider(this.blue, jSlider3);
        updateRGBTextField(this.blue, jTextField5, jTextField6);
      }
    }//GEN-LAST:event_hexTextFieldActionPerformed

    private void changeColor(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeColor
      JButton theButton = (JButton) evt.getSource();
      String name = theButton.getText();
      if (name.equalsIgnoreCase("Red")) {
        setSelectedColor(0xff, 0, 0);
      } else if (name.equalsIgnoreCase("Green")) {
        setSelectedColor(0, 0xff, 0);
      } else if (name.equalsIgnoreCase("Blue")) {
        setSelectedColor(0, 0, 0xff);
      } else if (name.equalsIgnoreCase("White")) {
        setSelectedColor(0xff, 0xff, 0xff);
      } else if (name.equalsIgnoreCase("Light Grey")) {
        setSelectedColor(0xbf, 0xbf, 0xbf);
      } else if (name.equalsIgnoreCase("Grey")) {
        setSelectedColor(0x7f, 0x7f, 0x7f);
      } else if (name.equalsIgnoreCase("Dark Grey")) {
        setSelectedColor(0x3f, 0x3f, 0x3f);
      } else if (name.equalsIgnoreCase("Black")) {
        setSelectedColor(0, 0, 0);
      } else if (name.equalsIgnoreCase("Maganta")) {
        setSelectedColor(0x00ff00ff);
      } else if (name.equalsIgnoreCase("Chestnut")) {
        setSelectedColor(0x00cd5c5c);
      } else if (name.equalsIgnoreCase("Maroon")) {
        setSelectedColor(0x00800000);
      } else if (name.equalsIgnoreCase("Mauve")) {
        setSelectedColor(0xe0b0ff);
      } else if (name.equalsIgnoreCase("Lime")) {
        setSelectedColor(0x00bfff00);
      } else if (name.equalsIgnoreCase("Sap Green")) {
        setSelectedColor(0x00507d2a);
      } else if (name.equalsIgnoreCase("Yellow")) {
        setSelectedColor(0x00ffff00);
      } else if (name.equalsIgnoreCase("Forest Green")) {
        setSelectedColor(0x00014421);
      } else if (name.equalsIgnoreCase("Cyan")) {
        setSelectedColor(0x0000ffff);
      } else if (name.equalsIgnoreCase("Royal Blue")) {
        setSelectedColor(0x00002366);
      } else if (name.equalsIgnoreCase("Klein Blue")) {
        setSelectedColor(0x00002fa7);
      } else if (name.equalsIgnoreCase("Indigo")) {
        setSelectedColor(0x004b0082);
      }
      updateDisplay();
    }//GEN-LAST:event_changeColor

    private void hueSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hueSliderStateChanged
      JSlider theSlider = (JSlider) evt.getSource();
      if (theSlider.getValueIsAdjusting()) {
        return;
      }
      double hue = jSlider4.getValue() / 100.0;
      double sat = jSlider5.getValue() / 100.0;
      double lightness = jSlider6.getValue() / 100.0;
      int rgb = Color.HSBtoRGB((float) hue, (float) sat, (float) lightness);
      setSelectedColor(rgb);

      updateRGBSlider(this.red, jSlider1);
      updateRGBTextField(this.red, jTextField1, jTextField2);
      updateRGBSlider(this.green, jSlider2);
      updateRGBTextField(this.green, jTextField3, jTextField4);
      updateRGBSlider(this.blue, jSlider3);
      updateRGBTextField(this.blue, jTextField5, jTextField6);

      updateHSLLabels((float) hue, (float) sat, (float) lightness);
    }//GEN-LAST:event_hueSliderStateChanged

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton11;
  private javax.swing.JButton jButton12;
  private javax.swing.JButton jButton13;
  private javax.swing.JButton jButton14;
  private javax.swing.JButton jButton15;
  private javax.swing.JButton jButton16;
  private javax.swing.JButton jButton17;
  private javax.swing.JButton jButton18;
  private javax.swing.JButton jButton19;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton20;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JSlider jSlider1;
  private javax.swing.JSlider jSlider2;
  private javax.swing.JSlider jSlider3;
  private javax.swing.JSlider jSlider4;
  private javax.swing.JSlider jSlider5;
  private javax.swing.JSlider jSlider6;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField3;
  private javax.swing.JTextField jTextField4;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JTextField jTextField6;
  // End of variables declaration//GEN-END:variables
}
